name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest
  deploy:
      name: Deploy to Kubernetes
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: List files and folders
          run: ls -R
          
        - name: Set up Kubernetes CLI
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'
  
        - name: Configure Kubernetes
          run: |
            kubectl config set-cluster kind --server="${{ secrets.NGROK_URL }}" --insecure-skip-tls-verify=true
            kubectl config set-credentials gitlab --token="${{ secrets.KUBERNETES_TOKEN }}"
            kubectl config set-context kind --cluster=kind --user=gitlab
            kubectl config use-context kind
  
        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f kubernetes/deployment.yaml --validate=false
            kubectl apply -f kubernetes/service.yaml --validate=false  
